language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # Build udagram-api-feed
  - cd $TRAVIS_BUILD_DIR/udagram-api-feed
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed eamonnh/udagram-api-feed:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push eamonnh/udagram-api-feed
  # Build udagram-api-user
  - cd $TRAVIS_BUILD_DIR/udagram-api-user
  - docker --version # print the version for logging
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user eamonnh/udagram-api-user:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push eamonnh/udagram-api-user
  # Build udagram-reverse-proxy
  - cd $TRAVIS_BUILD_DIR/udagram-reverse-proxy
  - docker --version # print the version for logging
  - docker build -t udagram-reverse-proxy .
  - docker tag udagram-reverse-proxy eamonnh/udagram-reverse-proxy:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push eamonnh/udagram-reverse-proxy

# Tasks to perform after the process is successful. 
after_success:
  - echo "Build completed"