apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: eamonnh/udagram-api-feed
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRESS_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRESS_USERNAME
        - name: POSTGRESS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRESS_PASSWORD
        - name: POSTGRESS_HOST
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRESS_HOST
        - name: POSTGRESS_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRESS_DATABASE
        - name: POSTGRESS_MEDIA_BUCKET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRESS_MEDIA_BUCKET
        - name: POSTGRESS_REGION
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRESS_REGION
        - name: POSTGRESS_PROFILE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: POSTGRESS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: JWT_SECRET

