apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api-user
  name: udagram-api-user
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-api-user
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: udagram-api-user
  sessionAffinity: None
  type: ClusterIP